# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # Custom built Centos6 image.
  config.vm.box = "geerlingguy/centos6"

  # Disable checking, because the box is not stored on public repo.
  config.vm.box_check_update = false

  # Setting up port forwading for both run.py, and the eventual wsgi container.
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
   config.vm.network "public_network"

  # Share the root of the repo, to the vagrantbox
    config.vm.synced_folder "../", "/repo"


  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
   config.vm.provision "shell", inline: <<-SHELL
     sudo yum -y install python-pip
     sudo pip install --upgrade pip
     sudo pip install flask
     sudo pip install nose
     sudo pip install sqlalchemy
     sudo yum install postgresql

   SHELL
end
